name: Docker Build and Push Image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push php 7 fpm image
        uses: docker/build-push-action@v2
        with:
          file: ./php7-amd64/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: martinussuherman/alpine-php-fpm:7-amd64

      - name: Build and push php 8 fpm image
        uses: docker/build-push-action@v2
        with:
          file: ./php8-amd64/Dockerfile
          context: .
          platforms: linux/amd64
          push: true
          tags: martinussuherman/alpine-php-fpm:8-amd64
